# Generated by Django 4.2 on 2024-11-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8, verbose_name='users balance'),
        ),
    ]
