# Generated by Django 4.2 on 2024-12-06 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_module', '0004_book_comment_copies_count_borrow_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_comment',
            name='copies_count',
        ),
        migrations.AddField(
            model_name='book',
            name='copies_count',
            field=models.PositiveIntegerField(default=0, verbose_name='how many copies of this book are available'),
        ),
    ]
